run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: "1.21"
  build-tags: []
  skip-dirs-use-default: true
  skip-files: []
  modules: []
  skip-dirs: []
  workspace: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - goimports
    - revive

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck